asgardeo/asgardeo-tomcat-saml-agent

README.md
=> Update doc references

README.md, io.asgardio.tomcat.saml.agent.sample/src/main/resources/sample-app.properties, io.asgardio.tomcat.saml.agent.sample/src/main/webapp/WEB-INF/web.xml, io.asgardio.tomcat.saml.agent.sample/src/main/webapp/home.jsp
=> Update SampleApp references

README.md, docs/integrating_with_java_source_project.md
=> Restructure README.md

Dockerfile
Add Dockerfile for the sample app
=> Dockerize the sample

README.md, create_service_provider.sh
=> Extract docker commands from script to the README.md

README.md
=> Improve instructions in README.md

.dockerignore, Dockerfile, io.asgardio.tomcat.saml.agent/src/main/java/io/asgardio/tomcat/saml/agent/SSOAgentContextEventListener.java, sample-app.properties
Resolves https://github.com/asgardio/asgardio-tomcat-saml-agent/issues/22
=> Implement sample app config support from environment variables

docs/integrating_with_java_source_project.md, io.asgardio.tomcat.saml.agent/src/main/java/io/asgardio/tomcat/saml/agent/SSOAgentContextEventListener.java, pom.xml, sample-app.properties
Related https://github.com/asgardio/asgardio-java-saml-sdk/issues/12
Need to bump Java SAML SDK version after https://github.com/asgardio/asgardio-java-saml-sdk/pull/13 is merged.
=> Implement functionality to infer public cert from string

.github/workflows/docker-image-builder.yml
=> Create GitHub Workflow for Docker Builds

io.asgardeo.tomcat.saml.agent/src/main/java/io/asgardeo/tomcat/saml/agent/SSOAgentContextEventListener.java
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-
=> Handle null values when resolving environment variables

sample-app.properties
[List all changes you want to add here. If you fixed an issue, please
add a reference to that issue as well.]
-
[Please describe any preconditions that need to be addressed before we
can merge this pull request.]
[List any possible follow-up actions here; for instance, testing data
migrations, software that we need to install on staging and production
environments.]
-
=> Disable response signing and SLO

io.asgardeo.tomcat.saml.agent.sample/src/main/webapp/error.jsp, io.asgardeo.tomcat.saml.agent.sample/src/main/webapp/home.jsp, io.asgardeo.tomcat.saml.agent.sample/src/main/webapp/theme.css
Index page
Home page with claims
Home page without claims
=> Update SAML sample pages

io.asgardeo.tomcat.saml.agent/src/main/java/io/asgardeo/tomcat/saml/agent/SSOAgentContextEventListener.java, pom.xml
$subject.
Fix https://github.com/asgardeo/asgardeo-tomcat-saml-agent/issues/40.
Merge after https://github.com/asgardeo/asgardeo-java-saml-sdk/pull/15
=> Skip keyStore configs if SkipTLS property is set.

io.asgardeo.tomcat.saml.agent.sample/src/main/resources/configuration-catalog.md, io.asgardeo.tomcat.saml.agent.sample/src/main/resources/sample-app.properties
$subject
Fix https://github.com/asgardeo/asgardeo-tomcat-saml-agent/issues/14.
=> Add configuration catalog and refactor .properties file.

io.asgardeo.tomcat.saml.agent/src/main/java/io/asgardeo/tomcat/saml/agent/SSOAgentContextEventListener.java, pom.xml
…
Fix https://github.com/asgardeo/asgardeo-tomcat-saml-agent/issues/40.
$subject.
After https://github.com/asgardeo/asgardeo-java-saml-sdk/pull/17
=> Skip keyStore configs if the properties are not included in the properties file.

io.asgardeo.tomcat.saml.agent.sample/src/main/resources/post_binding_request.html, io.asgardeo.tomcat.saml.agent.sample/src/main/webapp/WEB-INF/web.xml, io.asgardeo.tomcat.saml.agent/src/main/java/io/asgardeo/tomcat/saml/agent/SSOAgentContextEventListener.java, pom.xml
$subject.
**Before**
**After**
After https://github.com/asgardeo/asgardeo-java-saml-sdk/pull/19
=> Revamp the POST-binding redirect page in the sample.

pom.xml
Bump Asgardeo saml sdk version to the latest released version - v0.1.11
=> Bump Asgardeo saml sdk version to the latest released version

io.asgardeo.tomcat.saml.agent.sample/src/main/webapp/index.html
Remove OIDC references in the landing page
ASAP
None
=> Minor improvements to the landing page

pom.xml
Revamp dependencies in tomcat-saml-agent and upgrade saml SDK to the latest version.
=> Revamp dependencies in tomcat-saml-agent

pom.xml
Update the Asgardeo SAML SDK version to 0.1.15
=> Update the sdk version to the latest released one

io.asgardeo.tomcat.saml.agent.sample/src/main/resources/sample-app.properties
$subject
Fixes https://github.com/wso2-enterprise/asgardeo-product/issues/6230
=> Remove license header from config file

README.md
=> Update to customized discord link

.github/workflows/pr-builder.yml, codecov.yml, io.asgardeo.tomcat.saml.agent.sample/pom.xml, io.asgardeo.tomcat.saml.agent/pom.xml, pom.xml
This PR adds Codecov and JaCoCo configurations to the repository.
=> Add Codecov and JaCoCo configurations
